In [1]:
import numpy as np
import pandas as pd

# Import the data
data = pd.read_csv('test.csv', index_col = 0)
head = list(data)
print(data)
print(head)

     A  B  C  D  E  F  default
a11  0  0  1  0  1  1        1
a12  1  1  1  1  0  0        1
a13  0  0  0  0  1  1        1
b11  1  1  1  0  0  0        0
b12  0  0  1  1  0  1        0
b13  0  1  0  1  1  0        1
c11  1  0  1  0  1  0        1
c12  1  0  1  0  1  0        0
c13  0  1  0  0  0  1        0
d11  0  0  1  1  0  1        1
d12  1  1  0  0  1  0        0
d13  0  1  1  0  1  0        1
['A', 'B', 'C', 'D', 'E', 'F', 'default']


In [2]:
# If we want to combine 2 indicators, the total cases are 6x6 = 36 cases (including the case of same indicators)

# Number of indicators
num_indi = data.shape[1]
print(num_indi)

# Idea is, we create a matrix that shows the risk using each pair of indicators
risk = np.zeros(shape = [num_indi-1, num_indi-1])
num_contract = np.zeros(shape = [num_indi-1, num_indi-1])

# Loop over the indicators
row = range(0,data.shape[0]-1)

for i in head[:len(head)-2]:
    for j in head[:len(head)-2]:
        # Now, we refine by using the column i as the first priority, the column j follows as the secondary
        # Refine by column i first
        refined_i = data.loc[data.loc[:,i] == 0]
        # Refined data after i and j
        df = refined_i.loc[refined_i.loc[:,j] == 0]
        # Convert the index in numbers
        a = head.index(i)
        b = head.index(j)
        # Count the number of contracts
        num_contract[a,b] = df.shape[0]
        # Count the number of default contracts
        num_default = list(df.iloc[:,-1]).count(1)
        risk[a,b] = num_default/(data.shape[0])

7


In [3]:
print(risk)
print(num_contract)

[[0.41666667 0.25       0.16666667 0.25       0.08333333 0.        ]
 [0.25       0.33333333 0.08333333 0.25       0.08333333 0.        ]
 [0.16666667 0.08333333 0.16666667 0.08333333 0.         0.        ]
 [0.25       0.25       0.08333333 0.33333333 0.         0.        ]
 [0.08333333 0.08333333 0.         0.         0.16666667 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
[[7. 4. 3. 4. 3. 0.]
 [4. 6. 1. 4. 2. 0.]
 [3. 1. 4. 3. 1. 0.]
 [4. 4. 3. 8. 2. 0.]
 [3. 2. 1. 2. 5. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# The matrix risk indicates the risk of each combination, (i,j) elements is the risk if we combine the indicator i and j
# The num_contract matrix demonstrates the respective number of contracts